/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { CodeEditor } from './components/CodeEditor';
import { WiringStudio } from './components/WiringStudio';
import { BuildConsole } from './components/BuildConsole';
import { GeneratorModal } from './components/GeneratorModal';
import { SearchIntelModal } from './components/SearchIntelModal';
import { BeginnerGuideModal } from './components/BeginnerGuideModal';
import { AiChatTab } from './components/AiChatTab';
import { defaultProject } from './defaultProject';
import { Project, Diagnostic } from './types';
import { BookOpen, Sparkles, X, ChevronRight } from 'lucide-react';
import { generateProjectAi, analyzeCodeAi } from './services/aiService';

export default function App() {
  const [project, setProject] = useState<Project>(defaultProject);
  const [activeView, setActiveView] = useState<'split' | 'code' | 'wiring' | 'chat'>('split');
  const [isGeneratorOpen, setIsGeneratorOpen] = useState(false);
  const [isSearchIntelOpen, setIsSearchIntelOpen] = useState(false);
  const [isBeginnerGuideOpen, setIsBeginnerGuideOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCompiling, setIsCompiling] = useState(false);
  const [diagnostics, setDiagnostics] = useState<Diagnostic[]>([]);
  const [showWelcomeBanner, setShowWelcomeBanner] = useState(true);
  const [mobileSplitTab, setMobileSplitTab] = useState<'code' | 'wiring'>('code');

  // Analyze code whenever code changes
  useEffect(() => {
    const timer = setTimeout(async () => {
      try {
        const diags = await analyzeCodeAi(project.code, project.targetPlatform);
        setDiagnostics(diags || []);
      } catch (err) {
        console.error('Linter error:', err);
      }
    }, 600);

    return () => clearTimeout(timer);
  }, [project.code, project.targetPlatform]);

  // Code modification handler
  const handleCodeChange = (newCode: string) => {
    setProject((prev) => ({
      ...prev,
      code: newCode,
    }));
  };

  // Platform selection handler
  const handlePlatformChange = (newPlatform: string) => {
    setProject((prev) => ({
      ...prev,
      targetPlatform: newPlatform,
    }));
  };

  // Project generation handler
  const handleGenerate = async (prompt: string, platform: string, domain: string) => {
    setIsGenerating(true);
    try {
      const data = await generateProjectAi({ prompt, platform, domain });
      setProject(data);
      setIsGeneratorOpen(false);
    } catch (err) {
      console.error('Generate error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  // Virtual compile action
  const handleCompile = () => {
    setIsCompiling(true);
    setTimeout(() => {
      setIsCompiling(false);
    }, 1200);
  };

  // Apply diagnostic fix
  const handleApplyFix = (diag: Diagnostic) => {
    if (!diag.fixSuggestion) return;
    const lines = project.code.split('\n');
    if (diag.line > 0 && diag.line <= lines.length) {
      lines[diag.line - 1] = diag.fixSuggestion;
      const updatedCode = lines.join('\n');
      setProject((prev) => ({ ...prev, code: updatedCode }));
    }
  };

  // Apply code snippet or full sketch generated by AI in chat or intel
  const handleApplyCode = (snippet: string, replaceFull = false) => {
    const isFullSketch = replaceFull || (snippet.includes('void setup()') && snippet.includes('void loop()'));

    setProject((prev) => ({
      ...prev,
      code: isFullSketch ? snippet : `${snippet}\n\n${prev.code}`,
    }));

    // Switch to split view so the user immediately sees the generated code in the editor!
    if (activeView === 'chat') {
      setActiveView('split');
    }
  };

  return (
    <div className="flex flex-col h-[100dvh] min-h-[100dvh] max-h-[100dvh] w-screen overflow-hidden bg-[#070b14] text-[#e0e7ff]">
      {/* Top Header Navbar */}
      <Header
        currentPlatform={project.targetPlatform}
        onPlatformChange={handlePlatformChange}
        activeView={activeView}
        onViewChange={setActiveView}
        onOpenGenerator={() => setIsGeneratorOpen(true)}
        onOpenSearchIntel={() => setIsSearchIntelOpen(true)}
        onOpenBeginnerGuide={() => setIsBeginnerGuideOpen(true)}
        onCompile={handleCompile}
        isCompiling={isCompiling}
        isGenerating={isGenerating}
      />

      {/* Beginner Welcome Banner (Dismissible) */}
      {showWelcomeBanner && (
        <div className="bg-gradient-to-r from-blue-950 via-[#0c1833] to-[#070b14] border-b border-blue-500/30 px-3 py-1.5 sm:px-4 sm:py-2 flex items-center justify-between text-xs select-none flex-shrink-0">
          <div className="flex items-center space-x-2">
            <span className="w-5 h-5 rounded-full bg-blue-500/20 text-cyan-400 flex items-center justify-center font-bold text-[11px] border border-blue-400/40 flex-shrink-0">
              ⚡
            </span>
            <span className="font-semibold text-white text-[11px] sm:text-xs">New to Arduino & C++?</span>
            <span className="hidden md:inline text-blue-200 text-[11px]">
              VoltStar Code automatically routes pins and provides color-coded wiring schematics.
            </span>
            <button
              onClick={() => setIsBeginnerGuideOpen(true)}
              className="text-cyan-300 font-bold underline hover:text-cyan-200 flex items-center space-x-0.5 ml-1 text-[11px] sm:text-xs"
            >
              <span>5-Min Beginner Guide</span>
              <ChevronRight className="w-3 h-3" />
            </button>
          </div>

          <button
            onClick={() => setShowWelcomeBanner(false)}
            className="p-1 text-slate-400 hover:text-white rounded hover:bg-blue-900/40 flex-shrink-0"
            title="Dismiss"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* Main Workspace View */}
      <main className="flex-1 flex overflow-hidden relative">
        {/* VIEW 1: SPLIT VIEW (Code + Wiring) */}
        {activeView === 'split' && (
          <div className="flex-1 flex flex-col h-full overflow-hidden">
            {/* Mobile Sub-Switcher (< lg screens) */}
            <div className="flex lg:hidden bg-[#050812] border-b border-blue-950 px-3 py-1.5 justify-between items-center text-xs flex-shrink-0">
              <span className="text-slate-400 font-medium text-[11px]">View on Mobile:</span>
              <div className="flex bg-[#0b1324] p-0.5 rounded-lg border border-blue-900/60">
                <button
                  onClick={() => setMobileSplitTab('code')}
                  className={`px-3 py-1 rounded text-xs font-semibold transition-colors ${
                    mobileSplitTab === 'code' ? 'bg-blue-600 text-white shadow-sm' : 'text-slate-400 hover:text-white'
                  }`}
                >
                  💻 Code Editor
                </button>
                <button
                  onClick={() => setMobileSplitTab('wiring')}
                  className={`px-3 py-1 rounded text-xs font-semibold transition-colors ${
                    mobileSplitTab === 'wiring' ? 'bg-blue-600 text-white shadow-sm' : 'text-slate-400 hover:text-white'
                  }`}
                >
                  🔌 Wiring Studio
                </button>
              </div>
            </div>

            {/* Content area: dual column on desktop, selected tab on mobile */}
            <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 h-full overflow-hidden">
              {/* Left Column: Code Editor */}
              <div className={`${mobileSplitTab === 'code' ? 'block' : 'hidden'} lg:block lg:col-span-6 xl:col-span-6 h-full overflow-hidden border-r border-blue-950/70`}>
                <CodeEditor
                  code={project.code}
                  onChange={handleCodeChange}
                  diagnostics={diagnostics}
                  onApplyFix={handleApplyFix}
                  platform={project.targetPlatform}
                  projectTitle={project.projectTitle}
                />
              </div>

              {/* Right Column: Interactive Wiring Studio */}
              <div className={`${mobileSplitTab === 'wiring' ? 'block' : 'hidden'} lg:block lg:col-span-6 xl:col-span-6 h-full overflow-hidden`}>
                <WiringStudio project={project} />
              </div>
            </div>
          </div>
        )}

        {/* VIEW 2: FULL CODE VIEW */}
        {activeView === 'code' && (
          <div className="flex-1 h-full overflow-hidden">
            <CodeEditor
              code={project.code}
              onChange={handleCodeChange}
              diagnostics={diagnostics}
              onApplyFix={handleApplyFix}
              platform={project.targetPlatform}
              projectTitle={project.projectTitle}
            />
          </div>
        )}

        {/* VIEW 3: FULL WIRING STUDIO */}
        {activeView === 'wiring' && (
          <div className="flex-1 h-full overflow-hidden">
            <WiringStudio project={project} />
          </div>
        )}

        {/* VIEW 4: AI CHAT VIEW */}
        {activeView === 'chat' && (
          <div className="flex-1 h-full overflow-hidden">
            <AiChatTab
              project={project}
              onApplyCodeSnippet={handleApplyCode}
            />
          </div>
        )}
      </main>

      {/* Bottom Dock: Virtual Build Console & Live Serial Monitor */}
      <BuildConsole
        platform={project.targetPlatform}
        diagnostics={diagnostics}
        isCompiling={isCompiling}
        onRunCompile={handleCompile}
        onApplyFix={handleApplyFix}
      />

      {/* Beginner Guide Modal */}
      <BeginnerGuideModal
        isOpen={isBeginnerGuideOpen}
        onClose={() => setIsBeginnerGuideOpen(false)}
        onTryStarter={() => setIsGeneratorOpen(true)}
      />

      {/* Generator Modal */}
      <GeneratorModal
        isOpen={isGeneratorOpen}
        onClose={() => setIsGeneratorOpen(false)}
        onGenerate={handleGenerate}
        isGenerating={isGenerating}
        currentPlatform={project.targetPlatform}
      />

      {/* Google Search Intel Modal */}
      <SearchIntelModal
        isOpen={isSearchIntelOpen}
        onClose={() => setIsSearchIntelOpen(false)}
        onInsertCode={handleApplyCode}
        platform={project.targetPlatform}
      />
    </div>
  );
}
