/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { CodeEditor } from './components/CodeEditor';
import { WiringStudio } from './components/WiringStudio';
import { BuildConsole } from './components/BuildConsole';
import { GeneratorModal } from './components/GeneratorModal';
import { SearchIntelModal } from './components/SearchIntelModal';
import { BeginnerGuideModal } from './components/BeginnerGuideModal';
import { AiChatTab } from './components/AiChatTab';
import { defaultProject } from './defaultProject';
import { Project, Diagnostic } from './types';
import { BookOpen, Sparkles, X, ChevronRight } from 'lucide-react';

export default function App() {
  const [project, setProject] = useState<Project>(defaultProject);
  const [activeView, setActiveView] = useState<'split' | 'code' | 'wiring' | 'chat'>('split');
  const [isGeneratorOpen, setIsGeneratorOpen] = useState(false);
  const [isSearchIntelOpen, setIsSearchIntelOpen] = useState(false);
  const [isBeginnerGuideOpen, setIsBeginnerGuideOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isCompiling, setIsCompiling] = useState(false);
  const [diagnostics, setDiagnostics] = useState<Diagnostic[]>([]);
  const [showWelcomeBanner, setShowWelcomeBanner] = useState(true);

  // Analyze code whenever code changes
  useEffect(() => {
    const timer = setTimeout(async () => {
      try {
        const resp = await fetch('/api/analyze-code', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            code: project.code,
            platform: project.targetPlatform,
          }),
        });
        if (resp.ok) {
          const data = await resp.json();
          setDiagnostics(data.diagnostics || []);
        }
      } catch (err) {
        console.error('Linter error:', err);
      }
    }, 600);

    return () => clearTimeout(timer);
  }, [project.code, project.targetPlatform]);

  // Code modification handler
  const handleCodeChange = (newCode: string) => {
    setProject((prev) => ({
      ...prev,
      code: newCode,
    }));
  };

  // Platform selection handler
  const handlePlatformChange = (newPlatform: string) => {
    setProject((prev) => ({
      ...prev,
      targetPlatform: newPlatform,
    }));
  };

  // Project generation handler
  const handleGenerate = async (prompt: string, platform: string, domain: string) => {
    setIsGenerating(true);
    try {
      const resp = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, platform, domain }),
      });

      if (!resp.ok) throw new Error('Generation failed');
      const data = await resp.json();
      setProject(data);
      setIsGeneratorOpen(false);
    } catch (err) {
      console.error('Generate error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  // Virtual compile action
  const handleCompile = () => {
    setIsCompiling(true);
    setTimeout(() => {
      setIsCompiling(false);
    }, 1200);
  };

  // Apply diagnostic fix
  const handleApplyFix = (diag: Diagnostic) => {
    if (!diag.fixSuggestion) return;
    const lines = project.code.split('\n');
    if (diag.line > 0 && diag.line <= lines.length) {
      lines[diag.line - 1] = diag.fixSuggestion;
      const updatedCode = lines.join('\n');
      setProject((prev) => ({ ...prev, code: updatedCode }));
    }
  };

  // Apply code snippet or full sketch generated by AI in chat or intel
  const handleApplyCode = (snippet: string, replaceFull = false) => {
    const isFullSketch = replaceFull || (snippet.includes('void setup()') && snippet.includes('void loop()'));

    setProject((prev) => ({
      ...prev,
      code: isFullSketch ? snippet : `${snippet}\n\n${prev.code}`,
    }));

    // Switch to split view so the user immediately sees the generated code in the editor!
    if (activeView === 'chat') {
      setActiveView('split');
    }
  };

  return (
    <div className="flex flex-col h-screen w-screen overflow-hidden bg-[#070b14] text-[#e0e7ff]">
      {/* Top Header Navbar */}
      <Header
        currentPlatform={project.targetPlatform}
        onPlatformChange={handlePlatformChange}
        activeView={activeView}
        onViewChange={setActiveView}
        onOpenGenerator={() => setIsGeneratorOpen(true)}
        onOpenSearchIntel={() => setIsSearchIntelOpen(true)}
        onOpenBeginnerGuide={() => setIsBeginnerGuideOpen(true)}
        onCompile={handleCompile}
        isCompiling={isCompiling}
        isGenerating={isGenerating}
      />

      {/* Beginner Welcome Banner (Dismissible) */}
      {showWelcomeBanner && (
        <div className="bg-gradient-to-r from-blue-950 via-[#0c1833] to-[#070b14] border-b border-blue-500/30 px-4 py-2 flex items-center justify-between text-xs select-none">
          <div className="flex items-center space-x-2.5">
            <span className="w-5 h-5 rounded-full bg-blue-500/20 text-cyan-400 flex items-center justify-center font-bold text-[11px] border border-blue-400/40">
              ⚡
            </span>
            <span className="font-semibold text-white">New to Arduino & Electronics?</span>
            <span className="hidden sm:inline text-blue-200">
              VoltStar Code automatically routes pins and provides color-coded wiring schematics.
            </span>
            <button
              onClick={() => setIsBeginnerGuideOpen(true)}
              className="text-cyan-300 font-bold underline hover:text-cyan-200 flex items-center space-x-0.5 ml-1"
            >
              <span>Read the 5-Minute Beginner Guide</span>
              <ChevronRight className="w-3 h-3" />
            </button>
          </div>

          <button
            onClick={() => setShowWelcomeBanner(false)}
            className="p-1 text-slate-400 hover:text-white rounded hover:bg-blue-900/40"
            title="Dismiss"
          >
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* Main Workspace View */}
      <main className="flex-1 flex overflow-hidden relative">
        {/* VIEW 1: SPLIT VIEW (Code + Wiring) */}
        {activeView === 'split' && (
          <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 h-full overflow-hidden">
            {/* Left Column: Code Editor */}
            <div className="lg:col-span-6 xl:col-span-6 h-full overflow-hidden border-r border-blue-950/70">
              <CodeEditor
                code={project.code}
                onChange={handleCodeChange}
                diagnostics={diagnostics}
                onApplyFix={handleApplyFix}
                platform={project.targetPlatform}
                projectTitle={project.projectTitle}
              />
            </div>

            {/* Right Column: Interactive Wiring Studio */}
            <div className="lg:col-span-6 xl:col-span-6 h-full overflow-hidden">
              <WiringStudio project={project} />
            </div>
          </div>
        )}

        {/* VIEW 2: FULL CODE VIEW */}
        {activeView === 'code' && (
          <div className="flex-1 h-full overflow-hidden">
            <CodeEditor
              code={project.code}
              onChange={handleCodeChange}
              diagnostics={diagnostics}
              onApplyFix={handleApplyFix}
              platform={project.targetPlatform}
              projectTitle={project.projectTitle}
            />
          </div>
        )}

        {/* VIEW 3: FULL WIRING STUDIO */}
        {activeView === 'wiring' && (
          <div className="flex-1 h-full overflow-hidden">
            <WiringStudio project={project} />
          </div>
        )}

        {/* VIEW 4: AI CHAT VIEW */}
        {activeView === 'chat' && (
          <div className="flex-1 h-full overflow-hidden">
            <AiChatTab
              project={project}
              onApplyCodeSnippet={handleApplyCode}
            />
          </div>
        )}
      </main>

      {/* Bottom Dock: Virtual Build Console & Live Serial Monitor */}
      <BuildConsole
        platform={project.targetPlatform}
        diagnostics={diagnostics}
        isCompiling={isCompiling}
        onRunCompile={handleCompile}
        onApplyFix={handleApplyFix}
      />

      {/* Beginner Guide Modal */}
      <BeginnerGuideModal
        isOpen={isBeginnerGuideOpen}
        onClose={() => setIsBeginnerGuideOpen(false)}
        onTryStarter={() => setIsGeneratorOpen(true)}
      />

      {/* Generator Modal */}
      <GeneratorModal
        isOpen={isGeneratorOpen}
        onClose={() => setIsGeneratorOpen(false)}
        onGenerate={handleGenerate}
        isGenerating={isGenerating}
        currentPlatform={project.targetPlatform}
      />

      {/* Google Search Intel Modal */}
      <SearchIntelModal
        isOpen={isSearchIntelOpen}
        onClose={() => setIsSearchIntelOpen(false)}
        onInsertCode={handleApplyCode}
        platform={project.targetPlatform}
      />
    </div>
  );
}
